In [1]:
import numpy as np

## Vectors
- A Vector is an ordered finite list of numbers
- Elements of a vector can be called entries, coefficients, or components 
- The size (called the dimension or length) is the number of elements the vector contains.
- A vector of size $n$ is called an n-vector
- A 1-vector is considered to be the same as the number itself

In [33]:
assert np.array([1, 2, 3]).size == len(np.array([1, 2, 3]))

In [32]:
# A 1-vector is considered to be the same as the number itself
assert np.array(1.3) == 1.3

In [57]:
# Two vectors are equal if they have the same size and the entries are the same
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])

# array_equal returns True/False if the arrays are completely equal
np.array_equal(a, b)

True

In [58]:
# np.equal and the python == operator work similarly
# they compare each element
print(np.equal(np.array([1, 2]), np.array([1, 2])))
print(np.equal(np.array([5, 5]), np.array([1, 2])))
np.array([1, 2]) == np.array([1, 2])

[ True  True]
[False False]


array([ True,  True])

In [37]:
# Create clock or stacked vectors with np.concatenate
# https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html?highlight=concatenate#numpy.concatenate
c = np.concatenate((a, b))

assert c.size == a.size + b.size
c

array([1, 2, 3, 1, 2, 3])

In [36]:
c[1:3]

array([2, 3])