In [1]:
import numpy as np

# Vectors
- A Vector is an ordered finite list of numbers
- Elements of a vector can be called entries, coefficients, or components 
- The size (called the dimension or length) is the number of elements the vector contains.
- A vector of size $n$ is called an n-vector
- A 1-vector is considered to be the same as the number itself

In [2]:
# A vector of size n is called an n-vector
# x is a 3-vector
x = np.array([1, 2, 3])
x.size

3

### Built-in Python vs. numpy tools
- `len` is built into Python (for iterables) returns the size of the 1st dimension.
- The `.size` property from numpy arrays works the same way, only on 1 dimensional vectors
- We'll use `.size` since it's accurate

In [3]:
x = np.array([1, 2, 3])
len(x) == x.size

True

- The numpy `.size` propery is a mathematically accurate 
- Numpy's `.size` property == the *the total number of elements in the vector.*
- For this reason, use `.size` from here on out :)

In [4]:
# For vectors with more than 1 dimension, .size is mathematically accurate
y = np.array([x, x, x])
print("len(y) is", len(y))
print("y.size is", y.size)
y

len(y) is 3
y.size is 9


array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

### A 1-vector containing only one number is the same as the number itself
- The 1 vector containing a scalar is the same as that scalar

In [5]:
# A 1-vector is considered to be the same as the number itself
assert [1.3] != 1.3, "Python built-in lists are not proper vectors"
assert np.array(1.3) == 1.3, "A numpy array of a single number is the same as that number"

### Vector Equality
- Two vectors are equal if they have the same size and all the entries are the same

In [6]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])

# array_equal returns True/False if the arrays are completely equal
np.array_equal(a, b)

True

### Use `np.array_equals` to get the equality of vectors
- `np.equal` and Python's `==` operator work similarly
- They return an array of booleans..
- But this is not the same as a single boolean
- Favor `np.array_equal` to get a single boolean answer for comparing vectors

In [7]:
# np.equal and the python == operator work similarly
# they compare each element
# But they're not
np.equal(np.array([2, 1, 0]), np.array([5, 1, 2]))

array([False,  True, False])

### Block or stacked vectors
- Concatenating or stacking vectors puts them end to end, like boxcars
- Consider $c$ = [$a$, $b$]
- The size of $c$ is the sum of the sizes of $a$ and $b$
- If $a$ is $[1, 2]$ and $b$ is $[3, 4]$
- Then $c$ is the vector $[1, 2, 3, 4]$

In [8]:
# Create clock or stacked vectors with np.concatenate
# https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html?highlight=concatenate#numpy.concatenate
a = np.array([1, 2])
b = np.array([3, 4])
c = np.concatenate((a, b))

assert c.size == a.size + b.size
c

array([1, 2, 3, 4])

### Subvectors
- Consider $c = [a, b]$ where $a=[1, 2]$ and $b=[3, 4]$
- $a$ and $b$ are subvectors, or slices, of $c$
- $[ 2, 3]$ is also a subvector of $c$
- Python's `in` operator is insufficient for checking if a subvector exists in a vector.
- We'll use `np.isin` function

In [9]:
# [1, 2] is a subvector of [1, 2, 3, 4]
np.isin(a, c)

array([ True,  True])

In [10]:
# [3, 4] is a subvector of [1, 2, 3, 4]
np.isin(b, c)

array([ True,  True])

In [11]:
# 1-vector containing 3 is also a subvector of [1, 2, 3, 4]
np.isin(np.array(3), c)

array(True)

In [12]:
# [2,3]  is also a subvector of [1, 2, 3, 4]
np.isin(np.array([2, 3]), c)

array([ True,  True])