In [1]:
import numpy as np

# Vectors
- A Vector is an ordered finite list of numbers
- Elements of a vector can be called entries, coefficients, or components 
- The size (called the dimension or length) is the number of elements the vector contains.
- A vector of size $n$ is called an n-vector
- A 1-vector is considered to be the same as the number itself

In [2]:
# A vector of size n is called an n-vector
# x is a 3-vector
x = np.array([1, 2, 3])
x.size

3

### Built-in Python vs. numpy tools
- `len` is built into Python (for iterables) returns the size of the 1st dimension.
- The `.size` property from numpy arrays works the same way, only on 1 dimensional vectors
- We'll use `.size` since it's accurate - mathematically accurate

In [3]:
x = np.array([1, 2, 3])
len(x) == x.size

True

- The numpy `.size` propery is a mathematically accurate 
- Numpy's `.size` property == the *the total number of elements in the vector.*
- For this reason, use `.size` from here on out :)

In [4]:
# For vectors with more than 1 dimension, .size is mathematically accurate
y = np.array([x, x, x])
print("len(y) is", len(y))
print("y.size is", y.size)
y

len(y) is 3
y.size is 9


array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

### A 1-vector containing only one number is the same as the number itself
- The 1 vector containing a scalar is the same as that scalar

In [5]:
# A 1-vector is considered to be the same as the number itself
assert [1.3] != 1.3, "Python built-in lists are not proper vectors"
assert np.array(1.3) == 1.3, "A numpy array of a single number is the same as that number"

### Vector Equality
- Two vectors are equal if they have the same size and all the entries are the same

In [6]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])

# array_equal returns True/False if the arrays are completely equal
np.array_equal(a, b)

True

### Use `np.array_equals` to get the equality of vectors
- `np.equal` and Python's `==` operator work similarly
- They return an array of booleans..
- But this is not the same as a single boolean
- Favor `np.array_equal` to get a single boolean answer for comparing vectors

In [7]:
# np.equal and the python == operator work similarly
# they compare each element
# But they're not
np.equal(np.array([2, 1, 0]), np.array([5, 1, 2]))

array([False,  True, False])

### Block or stacked vectors
- Concatenating or stacking vectors puts them end to end, like boxcars
- Consider $c$ = [$a$, $b$]
- The size of $c$ is the sum of the sizes of $a$ and $b$
- If $a$ is $[1, 2]$ and $b$ is $[3, 4]$
- Then $c$ is the vector $[1, 2, 3, 4]$

In [8]:
# Create clock or stacked vectors with np.concatenate
# https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html?highlight=concatenate#numpy.concatenate
a = np.array([1, 2])
b = np.array([3, 4])
c = np.concatenate((a, b))

assert c.size == a.size + b.size
c

array([1, 2, 3, 4])

### Subvectors
- Consider $c = [a, b]$ where $a=[1, 2]$ and $b=[3, 4]$
- $a$ and $b$ are subvectors, or slices, of $c$
- $[ 2, 3]$ is also a subvector of $c$
- Python's `in` operator is insufficient for checking if a subvector exists in a vector.
- We'll use `np.isin` function

In [9]:
# [1, 2] is a subvector of [1, 2, 3, 4]
np.isin(a, c)

array([ True,  True])

In [10]:
# [3, 4] is a subvector of [1, 2, 3, 4]
np.isin(b, c)

array([ True,  True])

In [11]:
# 1-vector containing 3 is also a subvector of [1, 2, 3, 4]
np.isin(np.array(3), c)

array(True)

In [12]:
np.isin(3, c)

array(True)

In [13]:
# [2,3]  is also a subvector of [1, 2, 3, 4]
np.isin(np.array([2, 3]), c)

array([ True,  True])

### Indexing
- Vector indexes, in mathematics, start at 1
- In mathematical notation, for an $n$-vector, the index goes from $i=1$  to $i = n$
- Vector indexes, in Python/numpy, start at 0
- For Python indexing, indexes start at $i=0$ and go to $i=n-1$

### Zero vectors
- A zero vector is a vector with all elements equa to zero
- Sometimes the 0 vector is denoted with $0_n$, where $n$ is the size.
- Usually, a zero vector is denoted with just $0$ and the size is implied by that vector's context
- If $a$ is a 9-vector and we're told that $a=0$ then the $0$ on the right hand side must be of size 9.

In [14]:
# Python/numpy compares each element, rather than the whole vector/array
np.array([0, 0]) == 0

array([ True,  True])

In [15]:
# Setup a zero vector of size 9
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
# We get a boolean array w/ == 
a = np.array([0, 0, 0])
a == 0

array([ True,  True,  True])

In [17]:
# We get a boolean array when using .equal
a = np.array([0, 0, 0])
np.equal(a, 0)

array([ True,  True,  True])

In [18]:
# The mathematical notation here breaks down w/ Python
np.array_equal(a, 0)

False

In [19]:
# Comparing the numpy array of zeros to the python list of zeros returns true
np.array_equal(a, [0, 0, 0])

True

In [24]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [26]:
np.zeros((3, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [27]:
np.zeros((2, 2, 2, 2))

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])

## Ones Vector
- All the members are 1
- The vector 1 is sometimes called the ones vector.


In [20]:
np.ones(2)

array([1., 1.])

In [22]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [23]:
np.ones((3, 3, 3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

### Unit Vectors
- A vector will all elements zero except for one
- The $i$th unit-vector of size $n$ is the unit vector with $i$th element as its one value
- This is denoted $e_i$

In [32]:
e1 = np.array([1, 0, 0])
e2 = np.array([0, 1, 0])
e3 = np.array([0, 0, 1])
e4 = np.array([0, 0, 0, 1])

## Sparsity
- a vector is *sparse* if many of its entries are zero
- A zeros vector is the most sparse vector possible
- Unit vectors are sparese, since there's only one non-zero entry
- **nnz(x)** is a function of that tells us the number of non-zeros in a vector
- Sparse vectors arise in many applications